### PR TITLE
set bison requirement as per docs

### PR DESCRIPTION
**Pull request by GitMensch**
see #22

### CODE REVIEW

**Comment by GitMensch** [comment]
ping @mridoni for this and the other open PRs

**Comment by GitMensch** [comment]
friendly ping @mridoni again

**Comment by mridoni** [comment]
Hello, this has been fixed in v1.0.8 (and of course v1.0.9): gix_esql_parser.yy reports the correct version:

      %require "3.7"

(or am I missing something else)?

**Comment by GitMensch** [comment]
ah, yes, the merge would be a no-op. So "fixed with 1.0.8. :-)

**Pull request closed without merging**
