### PR TITLE
DBAUTH fix; logging added; markdown adjustments

### PR DESCRIPTION
**Pull request by GitMensch**

### CODE REVIEW

**Comment by GitMensch** [comment]
merge-conflicts fixed, ping @mridoni for possible integration

**Comment by GitMensch** [comment]
added the missing documentation about logging

**Comment by mridoni** [comment]
I saw your patch and I am all for documenting the logging feature, but this is only meant to be enabled on debug builds (the slowdown can easily be 10x) where debug is related to GixSQL itself, not to COBOL applications. This is also for security reasons, since the logs possibly leak any kind of sensitive data, which is fine if you are checking/testing a feature or bug in GixSQL, but obviously a big no-no in any other environment.

**Comment by GitMensch** [comment]
"it is meant to be only enabled" <> "it can only be enabled"

If it is actually only relevant for debug builds: then we don't need to document that at all, otherwise it would be good to have it enabled. Actually I wanted to suggest (after the release) that the logging is adjusted providing different levels (DEBUG/DBG, INFO/INF, WARNING/WARN/WAR, ERROR/ERR, OFF) with a default to ERR - this way the sensitive data would only be logged when explicit set to DEBUG (and that is possible for example with ODBC, too).

If "undecided" - just take the other parts over and we can document the logging later.

**Pull request merged**
